### ISSUE TITLE
缺少参数

### ISSUE THREAD

**Issue by UQJRlex** [zsakvo/dhbooker#7]
不知为何，总是提示【缺少参数】，用户名填的是手机号

![IMG_20190806_165359_1](https://user-images.githubusercontent.com/39591894/62526725-6ad78a00-b86c-11e9-8940-8d3a85305cfb.jpg)

**Comment by w-e-w** [comment]
你的問題跟config.ini沒關係

執行下載時 請在terminal/powershell/cmd裡輸入
./dhbooker **-b bookid** -t type -p timeout
至少要有 **-b bookid**

例如:
./dhbooker-win64.exe **-b 123456789**

注意要有 **-b**

可再額外加上 **-t txt** 或 **-t epub** 選擇輸出格式
例如:
./dhbooker-win64.exe -b 123456789 **-t txt**
./dhbooker-win64.exe -b 123456789 **-t epub**
預設格式為txt沒必要指定
-p timeout 一般不用改動

請參考
README.md
https://github.com/zsakvo/dhbooker#使用方法
