### ISSUE TITLE
panic: runtime error: index out of range

### ISSUE THREAD

**Issue by whiteloran** [zsakvo/dhbooker#8]
在按照要求填写好conf.ini，且对main.go进行了编译后，在执行时遇到了如下的问题：
p.s. 同样的问题在6月3日的issue里也出现过。

input:
>dhbooker-master -b ********

output:
>0 / 536 [----------------------------------------------------------------------------------------------------]   0.00%panic: runtime error: index out of range 
goroutine 186 [running]:
main.PKCS7UnPadding(...)
        D:/dhbooker-master/dhbooker-master/decode.go:53
main.AESDecrypt(0xc0013f20c2, 0x20, 0x9d9450, 0x0, 0x0, 0x0, 0x0, 0x0)
        D:/dhbooker-master/dhbooker-master/decode.go:46 +0x207
main.decode(0x0, 0x0, 0xc0013f20c2, 0x20, 0x0, 0x0)
        D:/dhbooker-master/dhbooker-master/decode.go:61 +0x9c
main.getChapterContent(0xc0003cf360, 0x9, 0x9, 0x740e56, 0x4)
        D:/dhbooker-master/dhbooker-master/ciweimao.go:167 +0xa41
main.writeChapterTemp(0xc0003cf360, 0x9, 0x218)
        D:/dhbooker-master/dhbooker-master/ciweimao.go:189 +0x105
created by main.downloadChapters
        D:/dhbooker-master/dhbooker-master/ciweimao.go:72 +0x13c

conf.ini
>username = ****
password = ****
tmp = E:\dhbook\tmp
out = E:\dhbook\out

想要请教一下，应该如何操作才能解决这个问题呢？谢谢。

**Comment by zsakvo** [comment]
本仓库已废弃，全新构建的版本在此，谢谢合作。
https://github.com/zsakvo/Cirno-go
